apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-software.fullname" . }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "jira-software.selectorLabels" . | nindent 4 }}
