output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "worker_iam_role_name" {
  description = "EKS Workers IAM Name"
  value       = module.eks.worker_iam_role_name
}

output "aws_account_id" {
  value = data.aws_caller_identity.current.account_id
}

output "efs-storage-fsid" {
  value = aws_efs_file_system.efs-storage.id
}

output "public_ips" {
  value = module.vpc.nat_public_ips
}

output "nat_ids" {
  value = module.vpc.nat_ids
}

output "natgw_ids" {
  value = module.vpc.natgw_ids
}

output "vpc_id" {
  value = module.vpc.vpc_id
}
